"""add_preference

Revision ID: 2d775b5ad3b4
Revises: 753594b8907c
Create Date: 2026-03-09 16:29:41.881957

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d775b5ad3b4'
down_revision: Union[str, Sequence[str], None] = '753594b8907c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('preferences', sa.Column('user_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('preferences_profile_id_fkey'), 'preferences', type_='foreignkey')
    op.create_foreign_key(None, 'preferences', 'users', ['user_id'], ['id'])
    op.drop_column('preferences', 'profile_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('preferences', sa.Column('profile_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'preferences', type_='foreignkey')
    op.create_foreign_key(op.f('preferences_profile_id_fkey'), 'preferences', 'profiles', ['profile_id'], ['id'])
    op.drop_column('preferences', 'user_id')
    # ### end Alembic commands ###
