"""add_index

Revision ID: 4d34ee607693
Revises: 9af1aa5eb985
Create Date: 2026-03-22 11:05:39.656968

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d34ee607693'
down_revision: Union[str, Sequence[str], None] = '9af1aa5eb985'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_preferences_user_gender_age', 'preferences', ['user_id', 'gender', 'age'], unique=False)
    op.create_index(op.f('ix_preferences_user_id'), 'preferences', ['user_id'], unique=False)
    op.create_index('ix_profiles_search', 'profiles', ['gender', 'city', 'age', 'user_id'], unique=False)
    op.create_index(op.f('ix_profiles_user_id'), 'profiles', ['user_id'], unique=False)
    op.create_index(op.f('ix_swipes_user1'), 'swipes', ['user1'], unique=False)
    op.create_index('ix_swipes_user1_user2', 'swipes', ['user1', 'user2'], unique=True)
    op.create_index(op.f('ix_swipes_user2'), 'swipes', ['user2'], unique=False)
    op.create_index('ix_swipes_user2_user1', 'swipes', ['user2', 'user1'], unique=False)
    op.create_unique_constraint('uq_swipes_user1_user2', 'swipes', ['user1', 'user2'])
    op.create_foreign_key(None, 'swipes', 'users', ['user2'], ['id'])
    op.create_foreign_key(None, 'swipes', 'users', ['user1'], ['id'])
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_constraint(None, 'swipes', type_='foreignkey')
    op.drop_constraint(None, 'swipes', type_='foreignkey')
    op.drop_constraint('uq_swipes_user1_user2', 'swipes', type_='unique')
    op.drop_index('ix_swipes_user2_user1', table_name='swipes')
    op.drop_index(op.f('ix_swipes_user2'), table_name='swipes')
    op.drop_index('ix_swipes_user1_user2', table_name='swipes')
    op.drop_index(op.f('ix_swipes_user1'), table_name='swipes')
    op.drop_index(op.f('ix_profiles_user_id'), table_name='profiles')
    op.drop_index('ix_profiles_search', table_name='profiles')
    op.drop_index(op.f('ix_preferences_user_id'), table_name='preferences')
    op.drop_index('ix_preferences_user_gender_age', table_name='preferences')
    # ### end Alembic commands ###
