"""add_tg

Revision ID: 729a7e18fd11
Revises: 74136df4d688
Create Date: 2026-03-17 18:11:23.108440

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '729a7e18fd11'
down_revision: Union[str, Sequence[str], None] = '74136df4d688'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('tg_username', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'tg_username')
    # ### end Alembic commands ###
