"""add_tg_1

Revision ID: 9af1aa5eb985
Revises: 729a7e18fd11
Create Date: 2026-03-20 16:45:35.661617

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9af1aa5eb985'
down_revision: Union[str, Sequence[str], None] = '729a7e18fd11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('telegram_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'telegram_id')
    # ### end Alembic commands ###
